AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
  BucketName:
    Type: String
    Description: "The name of the S3 bucket"
    Default: "roshsecondfirstyadav"  # Add a default value if necessary

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0ff8a91507f77f867
    us-west-1:
      AMI: ami-0bdb828fd58c52235

Resources:
  MysecondVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MysecondVPC

  MysecondSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MysecondVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: MysecondSubnet

  MysecondInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      SubnetId: !Ref MysecondSubnet

  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  VPCId:
    Value: !Ref MysecondVPC
  SubnetId:
    Value: !Ref MysecondSubnet
  InstanceId:
    Value: !Ref MysecondInstance
  InstancePublicIP:
    Value: !GetAtt MysecondInstance.PublicIp
  BucketName:
    Value: !Ref MyBucket
