name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: ls -R

      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body file://template.yaml

      - name: Deploy CloudFormation stack
        run: |
          STACK_NAME=my-cloudformation-stack
          TEMPLATE_FILE=template.yaml
          BUCKET_NAME=roshsecond # Ensure this is a unique name and correctly provided

          # Check if stack exists
          if aws cloudformation describe-stacks --stack-name $STACK_NAME; then
            echo "Updating stack..."
            aws cloudformation update-stack --stack-name $STACK_NAME --template-body file://$TEMPLATE_FILE --parameters ParameterKey=BucketName,ParameterValue=$BUCKET_NAME --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation wait stack-update-complete --stack-name $STACK_NAME
          else
            echo "Creating stack..."
            aws cloudformation create-stack --stack-name $STACK_NAME --template-body file://$TEMPLATE_FILE --parameters ParameterKey=BucketName,ParameterValue=$BUCKET_NAME --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation wait stack-create-complete --stack-name $STACK_NAME
          fi
